### ISSUE TITLE
Consider enumerating value for "low" and "high" tension in the teacher tips

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/wave-on-a-string#114]
@arouinfar a teacher that wrote phethelp was curious about knowing the values of "low" and "high" tension. Might be good to include in the teaching tips.

In addition, being how popular this sim is, we should get teaching tips uploaded soonish.

**Comment by arouinfar** [comment]
Sounds like a good idea @ariel-phet. Do you happen to know what "low" and "high" correspond to? 

From the design doc
>  Reduce range of tension slider to 3 positions: Lo Med Hi.  These three positions are positions 8,9, and 10 on the current tension slider.  The reason for restricting tension to the 3 highest values is to prevent aliasing when frequency is high and tension is low

I checked Unfuddle to see if there was any documentation of the Flash model, but couldn't find anything other than the Teacher Tips (which doesn't list the value of the tension).

**Comment by arouinfar** [comment]
I could probably determine the value experimentally, but it seems wiser to check the source code for the value.

**Comment by ariel-phet** [comment]
@arouinfar seems best to ask @dubson about this. Try emailing him, but I am guessing it might be tough to get a response until after finals/grades are done.

**Comment by arouinfar** [comment]
Talked to @dubson this morning, and he will provide me with the tension values. I'll get the Teacher Tips up sometime this week.

**Comment by arouinfar** [comment]
I haven't heard back from @dubson, so I did some digging into WOASModel.js to see if I could figure it out. After talking to @phet-steele and @jbphet, it looks like the tension slider does not actually correspond to specific values. Instead, it is given a 0, 1, or 2. The tension effect is then displayed through the time step.

Line 34
> tension: 2, // tension 0..2

Lines 160-161 (fps hardcoded as 50)
> //dt for tension effect
      var minDt = (1 / (fps * (0.2 + this.tension * 0.4) * this.speed));

I took some data to see if the slider behaved linearly (i.e. the difference between Low and Middle  = the difference between Middle and High). I plotted Tension vs. Velocity Squared (with arbitrary tension values), which <i>should</i> have a linear relationship, with the linear mass density representing the slope.

If I assume the tension slider behaves linearly (like many teachers probably will), the data isn't quite linear.  It's hard to make an assessment with three data points, so I took a look at the Flash version, since we requested that the behavior match. The Flash data is definitely not linear, which means the slider does not behave linearly. 
![image](https://cloud.githubusercontent.com/assets/8419308/16661279/7a4e753e-442f-11e6-8924-5de86d5c4e6c.png)

If we assume the tension slider behaves logarithmically (notches go like 1, 10, 100...), the data still doesn't work out. 

If we make the assumption that the tension slider goes with powers of 2 (1, 2, 4, or even 128, 256, 1024) the data seems to behave linearly.
![image](https://cloud.githubusercontent.com/assets/8419308/16661660/3db2a81e-4431-11e6-9178-30cf1ac1015b.png)

I'll reach out to @dubson to confirm the slider scale. However, I won't be able to provide teachers with the precise values of the tension, but I can make a note about their relationship to one another.

**Comment by arouinfar** [comment]
After going through this exercise, however, I wonder if we have too severely limited the ability of the HTML5 sim to address learning goals related to tension and speed. I wouldn't be surprised if some teachers deliberately use the Flash version, which has 11 tension notches.

**Comment by arouinfar** [comment]
WOAS tips have been uploaded. Closing.
